---
- hosts: all
  tasks:
    - name: check that nginx was well deployed
      uri:
        url: "http://{{ ansible_host }}:80"
        return_content: yes
        validate_certs: no
      register: result
      failed_when: "'Ansible' not in result.content"
