---
- hosts: all
  become: true
  pre_tasks:

    - name: insure vars are well transmitted
      assert:
        that:
          - nginx_action is defined and nginx_action != ""
        fail_msg: "variable 'nginx_action' must be 'install' or 'uninstall'"

  tasks:

    - include_role:
        name: role_install_nginx
      vars:
        state: "{{ nginx_action }}"

  post_tasks:

    - name: check that nginx was well deployed
      uri:
        url: "http://{{ ansible_host }}:80"
        return_content: yes
        validate_certs: no
      register: result
      failed_when: "'Ansible' not in result.content"
      when: nginx_action == 'install'

    - debug:
        msg: "NGINX WAS SUCCESSFULLY {{ nginx_action | upper | append('ED')}}"