---
- hosts: all
  become: true
  pre_tasks:

    - name: insure vars are well transmitted
      assert:
        that:
          - nginx_action is defined and nginx_action != ""
        fail_msg: "variable 'nginx_action' must be 'install' or 'uninstall'"

  tasks:

    - include_role:
        name: role_install_nginx
      vars:
        state: "{{ nginx_action }}"

  post_tasks:
    - debug:
        msg: "NGINX WAS SUCCESSFULLY {{ nginx_action | upper + 'ED' }}"