---
- name: Install nginx
  hosts: all
  become: true
  tasks:

    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Insert Index Page
      copy:
        src: ./files/index.html
        dest: /usr/share/nginx/html/index.html

    - name: Insert ansible logo
      copy:
        src: ./files/ansible-logo.jpg
        dest: /usr/share/nginx/html/ansible-logo.jpg

    - name: Start NGiNX
      service:
        name: nginx
        state: started
